# Generated by Django 3.1.7 on 2023-03-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.CharField(blank=True, max_length=7, null=True, verbose_name='الفصل')),
                ('capasity', models.IntegerField(blank=True, null=True, verbose_name='العدد')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('KG1', 'KG1'), ('KG2', 'KG2'), ('الأول الإبتدائي', 'الأول الإبتدائي'), ('الثاني الإبتدائي', 'الثاني الإبتدائي'), ('الثالث الإبتدائي', 'الثالث الإبتدائي'), ('الرابع الإبتدائي', 'الرابع الإبتدائي'), ('الخامس الإبتدائي', 'الخامس الإبتدائي'), ('السادس الإبتدائي', 'السادس الإبتدائي'), ('الأول الإعدادي', 'الأول الإعدادي'), ('الثاني الإعدادي', 'الثاني الإعدادي'), ('الثالث الإعدادي', 'الثالث الإعدادي')], max_length=20, null=True, verbose_name='الصف')),
                ('typee', models.CharField(blank=True, choices=[('عربي', 'عربي'), ('لغات', 'لغات')], max_length=20, null=True, verbose_name='اللغة')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم')),
                ('telphone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('clas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.classes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.level'),
        ),
    ]
